apiVersion: v1
kind: Service
metadata:
  name: nebula
  labels:
    app: nebula
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nebula
  type: ClusterIP
